version:  '3.9'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - erp-microservices-network
    volumes:
      - "D:/WorkDir/SharedTools/mongodb:/data/db"
    restart: always

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - erp-microservices-network
    restart: always

  auth-service:
    build: ./AuthService
    image: auth-service:latest
    ports:
      - "8080:8080"
    networks:
      - erp-microservices-network
    restart: always
    depends_on:
      - "mongodb"
      - "rabbitmq"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MONGODB_URL=mongodb://mongodb:27017/auth-service
      - SECRET_KEY=3FBE9D2EF4

  product-service:
    build: ./ProductService
    image: product-service:latest
    ports:
      - "8081:8081"
    networks:
      - erp-microservices-network
    restart: always
    depends_on:
      - "mongodb"
      - "rabbitmq"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MONGODB_URL=mongodb://mongodb:27017/product-service
      - SECRET_KEY=3FBE9D2EF4
      - AUTH_SERVER=http://auth-service:8080

  shopping-cart-service:
    build: ./ShoppingCartService
    image: shopping-cart-service:latest
    ports:
      - "8082:8082"
    networks:
      - erp-microservices-network
    restart: always
    depends_on:
      - "mongodb"
      - "rabbitmq"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - MONGODB_URL=mongodb://mongodb:27017/shopping-cart-service
      - SECRET_KEY=3FBE9D2EF4
      - AUTH_SERVER=http://auth-service:8080

networks:
  erp-microservices-network: {}